export const JOB_TYPELOAD_REQUEST = "JOB_LOAD_REQUEST";
export const JOB_TYPELOAD_SUCCESS = "JOB_LOAD_SUCCESS";
export const JOB_TYPELOAD_FAIL = "JOB_LOAD_FAIL";
export const JOB_TYPELOAD_RESET = "JOB_LOAD_RESET";

